# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='/static/uploads/', width_field='width_field'),
        ),
    ]
