# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20161210_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_1170',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
