# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20161211_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
