# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20161212_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
