# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20161212_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='posts',
            new_name='post',
        ),
    ]
