# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20161212_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_num',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
