# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_post_comment_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_time']},
        ),
    ]
