# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('total_times_of_visiting', models.CharField(max_length=10)),
                ('ip_addr', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
