# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20170103_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='total_times_of_visiting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
